name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - '*' # minden branch-en fusson

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate image tag
        id: image_tag
        run: |
          RUN_NUM=$(printf "%03d" ${{ github.run_number }})
          TAG="v$(date +%Y%m%d).$RUN_NUM"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Azure Container Registry login
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin     

      - name: List files
        run: ls -l ${{ github.workspace }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/profilplusz-oms:${{ env.IMAGE_TAG }}"
          docker build -t $IMAGE_NAME -f ${{ github.workspace }}/Dockerfile ${{ github.workspace }}

      - name: Push Docker image to ACR
        run: |
          IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/profilplusz-oms:${{ env.IMAGE_TAG }}"
          docker push $IMAGE_NAME

      - name: GitHub tag létrehozása az IMAGE_TAG alapján
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag $IMAGE_TAG || echo "Tag már létezik, kihagyva."
          git push origin $IMAGE_TAG || echo "Tag push sikertelen vagy már létezik."
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

      - name: Save image name
        run: |
          echo "${{ secrets.ACR_LOGIN_SERVER }}/profilplusz-oms:${{ env.IMAGE_TAG }}" > image.txt

      - name: Upload image name artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-name
          path: image.txt
