name: 04 - Deploy to Azure Web App from ACR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      image_tag:
        description: 'Select image tag to deploy'
        required: true
        type: choice
        options:
          - 0.1
          - 0.2
          - latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set variables
        run: |
          echo "RESOURCE_GROUP=profilplusz-${{ github.event.inputs.environment }}-rg" >> $GITHUB_ENV
          echo "WEBAPP_NAME=profilplusz-webapp-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Set image name
        run: |
          IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/profilplusz-oms:${{ github.event.inputs.image_tag }}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Update Web App image
        run: |
          az webapp config container set --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $IMAGE_NAME \
            --docker-registry-server-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      - name: Output webapp name
        run: |
          echo "Web App Name: $WEBAPP_NAME"
