name: Build and deploy ASP.NET app to Azure Web App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # vagy a projekted verziója

      - name: Restore dependencies
        run: dotnet restore ./Presentation/ASPNET/ASPNET.csproj

      - name: Build
        run: dotnet build ./Presentation/ASPNET/ASPNET.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Presentation/ASPNET/ASPNET.csproj --configuration Release --output ./publish --no-build

      - name: Run tests
        run: dotnet test ./Tests/Application.Tests/Application.Tests.csproj --no-build --verbosity normal

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
