name: 03 - WebApp Deploy

on:
  workflow_run:
    workflows: [ "Build and Push Docker image to ACR" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=profilplusz-${{ github.event.inputs.environment }}-rg" >> $GITHUB_ENV
          echo "SQL_SERVER_NAME=profilpluszsql${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "SQL_ADMIN_USER=${{ secrets.SQL_ADMIN_USER }}" >> $GITHUB_ENV
          echo "SQL_ADMIN_PASS=${{ secrets.SQL_ADMIN_PASS }}" >> $GITHUB_ENV
          echo "SQL_DB_NAME=profilplusz${{ github.event.inputs.environment }}db" >> $GITHUB_ENV
          echo "APP_SERVICE_PLAN=profilplusz-${{ github.event.inputs.environment }}-plan" >> $GITHUB_ENV
          echo "WEBAPP_NAME=profilplusz-webapp-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Download image name artifact
        uses: actions/download-artifact@v4
        with:
          name: image-name
          path: .

      - name: Read image name
        id: read_image
        run: |
          IMAGE_NAME=$(cat image.txt)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Create Web App (custom container from ACR)
        run: |
          az webapp create --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --deployment-container-image-name $IMAGE_NAME --docker-registry-server-url https://${{ secrets.ACR_LOGIN_SERVER }} --docker-registry-server-user ${{ secrets.ACR_USERNAME }} --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      - name: Set connection string
        run: |
          az webapp config connection-string set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --settings DefaultConnection="Server=tcp:$SQL_SERVER_NAME.database.windows.net,1433;Initial Catalog=$SQL_DB_NAME;Persist Security Info=False;User ID=$SQL_ADMIN_USER;Password=$SQL_ADMIN_PASS;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" --connection-string-type SQLAzure

      - name: Output webapp name
        run: |
          echo "Web App Name: $WEBAPP_NAME"

