name: BuildAndPush2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "my-image:latest" > image.txt
      - uses: actions/upload-artifact@v4
        with:
          name: image-name
          path: image.txt
